version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Install dependencies needed for running tests
      - mkdir -p common-layers/nodejs
      - cp -a package.json common-layers/nodejs
      - cd common-layers/nodejs && yarn
      # Install node_modules
      - cd - && yarn
      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

  build:
    commands:
      # Run unit tests
      # - yarn test
      # Use cloudformation to packaged it and push to S3
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET_NAME --output-template-file packaged-template.yml
    #finally:
      #- Build command failures
  post_build:
    commands:
      # Use cloudformation deploy
      # You can use --parameter-overrides to overrides parameters in template.yml
      # Example: aws cloudformation deploy --parameter-overrides Stage=Stg Region=ap-northeast-1
      - aws cloudformation deploy --template-file packaged-template.yml --stack-name creka-tasks-dev --capabilities CAPABILITY_NAMED_IAM --parameter-overrides CodeDeployRole=$DEPLOY_ROLE
artifacts:
  type: zip
  files:
    - packaged-template.yml
